---
abstract: 'It is an extension of the module Mojolicious::Plugin::Model'
author:
  - 'Lucas Tiago de Moraes <lucastiagodemoraes@gmail.com>'
build_requires:
  Class::Method::Modifiers: '0'
  ExtUtils::MakeMaker: '0'
  Mojo::SQLite: '2.000'
  Mojolicious::Plugin::Model: '0.13'
  Storable: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.44, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-Model-DB
no_index:
  directory:
    - t
    - inc
requires:
  Class::Method::Modifiers: '0'
  Mojolicious::Plugin::Model: '0.13'
  Storable: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/lucas1/Mojolicious-Plugin-Model-DB/issues
  homepage: https://github.com/lucas1/Mojolicious-Plugin-Model-DB
  repository: https://github.com/lucas1/Mojolicious-Plugin-Model-DB
version: '1.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
